# ============================================================================
# AI Coding Rules — Makefile
# Development automation. Docs: docs/USING_DEV_CLI.md
# Supported platforms: macOS (darwin), Linux. Works with GNU Make 3.81+.
#
# Help is generated by scripts/dev_info.py from this file: `##@ Section`
# lines start a help category and `target: ## description` lines list a
# target. Targets without `##` are hidden.
# ============================================================================

SHELL := /bin/bash
.DEFAULT_GOAL := help

# Overridable on the command line or from the environment.
UV ?= uv
UV_PYTHON ?= 3.12
PYTHON_VERSION ?= $(UV_PYTHON)
FORCE ?= 0
DRY_RUN ?= 0
CLI_ARGS ?=

export PYTHONDONTWRITEBYTECODE := 1

# Single-quote a value for the shell: $(call shq,value)
shq = '$(subst ','"'"',$(1))'
# Stop with a usage message when a variable is empty: $(call require,VAR,usage)
require = $(if $(strip $($(1))),,$(error $(1) is required. Usage: $(2)))

UV_Q = $(call shq,$(UV))
PY_Q = $(call shq,$(PYTHON_VERSION))
UV_RUN = $(UV_Q) run --locked --python $(PY_Q)
UNAME := $(shell uname)
# Composite targets call $(MAKE) once per step so steps run in order, even
# under -j, and make -n prints every step without running it.
MAKEFLAGS += --no-print-directory

MARKDOWN_RULES_TARGETS := rules/
MARKDOWN_DOCS_TARGETS := docs/ README.md CONTRIBUTING.md CHANGELOG.md
SHELL_SCRIPTS := scripts/maintainer-common.sh scripts/release.sh scripts/clean.sh scripts/plugin-verify.sh

.PHONY: help check-uv
help: check-uv ## Show categorized targets
	@UV=$(UV_Q) $(UV_RUN) python scripts/dev_info.py help

# Preflight shared by every target that runs uv.
check-uv:
	@command -v $(UV_Q) >/dev/null 2>&1 || { echo 'uv not found. Install from https://docs.astral.sh/uv/ or set UV to its executable path.' >&2; exit 1; }

##@ Environment

.PHONY: env-setup env-sync env-sync-live env-lock
env-setup: check-uv ## Pin Python (PYTHON_VERSION, default 3.12) and create .venv
	$(UV_Q) python install $(PY_Q)
	$(UV_Q) python pin $(PY_Q)
	$(UV_Q) venv --python $(PY_Q)

env-sync: check-uv ## Sync locked development dependencies
	$(UV_Q) sync --locked --python $(PY_Q) --no-group live-agent

env-sync-live: check-uv ## Opt in to locked live-agent dependencies
	$(UV_Q) sync --locked --python $(PY_Q) --group live-agent

env-lock: check-uv ## Update lockfile and sync development dependencies
	$(UV_Q) lock
	@$(MAKE) env-sync

##@ Quality

.PHONY: quality-all quality-all-fix quality-lint quality-lint-fix quality-format quality-format-fix
.PHONY: quality-typecheck quality-markdown quality-markdown-fix quality-automation
quality-all: ## Run Python, Markdown, and automation checks
	@$(MAKE) quality-lint
	@$(MAKE) quality-format
	@$(MAKE) quality-typecheck
	@$(MAKE) quality-markdown
	@$(MAKE) quality-automation

quality-all-fix: ## Apply Python and Markdown fixes, then check all quality gates
	@$(MAKE) quality-lint-fix
	@$(MAKE) quality-format-fix
	@$(MAKE) quality-markdown-fix
	@$(MAKE) quality-all

quality-lint: check-uv ## Run Ruff linter without fixes
	$(UV_RUN) ruff check .

quality-lint-fix: check-uv ## Apply Ruff lint fixes
	$(UV_RUN) ruff check --fix .

quality-format: check-uv ## Check Python formatting
	$(UV_RUN) ruff format --check .

quality-format-fix: check-uv ## Apply Python formatting
	$(UV_RUN) ruff format .

quality-typecheck: check-uv ## Run ty type checker
	$(UV_RUN) ty check .

quality-markdown: check-uv ## Check rules and documentation Markdown
	$(UV_RUN) pymarkdownlnt --config pymarkdown.rules.json scan $(MARKDOWN_RULES_TARGETS)
	$(UV_RUN) pymarkdownlnt --config pymarkdown.docs.json scan $(MARKDOWN_DOCS_TARGETS)

quality-markdown-fix: check-uv ## Fix rules and documentation Markdown
	$(UV_RUN) pymarkdownlnt --config pymarkdown.rules.json fix $(MARKDOWN_RULES_TARGETS)
	$(UV_RUN) pymarkdownlnt --config pymarkdown.docs.json fix $(MARKDOWN_DOCS_TARGETS)

quality-automation: check-uv ## Validate the Makefile, shell syntax, lint, and formatting
	@command -v shellcheck >/dev/null 2>&1 || { echo 'Install ShellCheck to validate automation scripts.' >&2; exit 1; }
	@command -v shfmt >/dev/null 2>&1 || { echo 'Install shfmt to check shell formatting.' >&2; exit 1; }
	@$(MAKE) -n help >/dev/null
	shellcheck -x -P scripts $(SHELL_SCRIPTS)
	shfmt -d -i 2 -ci $(SHELL_SCRIPTS)

##@ Testing

.PHONY: test-run test-automation test-coverage test-coverage-open
test-run: check-uv ## Run pytest tests (extra pytest arguments: CLI_ARGS="...")
	$(UV_RUN) pytest tests/ --tb=short $(CLI_ARGS)

test-automation: check-uv ## Test automation using disposable repositories and command stubs
	$(UV_RUN) pytest tests/automation/ tests/test_version_consistency.py --tb=short

test-coverage: check-uv ## Run tests and enforce coverage threshold
	$(UV_RUN) pytest --cov=src/ai_rules --cov-report=term-missing --cov-report=html tests/

test-coverage-open: ## Run coverage and open HTML report on macOS
ifeq ($(UNAME),Darwin)
	@$(MAKE) test-coverage
	open htmlcov/index.html
else
	@echo 'test-coverage-open runs on macOS only; skipping.'
endif

##@ Validation

.PHONY: validate ci validate-schemas validate-rule-loader
# Runs every gate in order for one interpreter. Hosted CI also tests Python
# 3.13 and automation on macOS and Linux. Cortex loader validation is optional;
# use plugin-verify-strict when Cortex must be present.
validate: ## Full validation including coverage and rule-loader contracts
	@$(MAKE) status-preflight
	@$(MAKE) quality-all
	@$(MAKE) test-coverage
	@$(MAKE) validate-schemas
	@$(MAKE) validate-rule-loader
	@$(MAKE) plugin-verify

ci: validate ## Alias for validate

validate-schemas: check-uv ## Validate rule, example, template, and skill schemas
	$(UV_RUN) ai-rules validate rules/
	$(UV_RUN) ai-rules validate rules/examples/ --examples
	$(UV_RUN) ai-rules validate templates/ --templates
	$(UV_RUN) ai-rules validate-skills skills/

validate-rule-loader: check-uv ## Validate fixtures, corpus reachability, and trigger-count contract
	$(UV_RUN) ai-rules rule-loader validate
	$(UV_RUN) ai-rules rule-loader audit --fail-on-miss
	$(UV_RUN) ai-rules rule-loader validate-trigger-contract

##@ Plugin

.PHONY: plugin-verify plugin-verify-strict
plugin-verify: check-uv ## Check plugin fidelity; check Cortex loader when installed
	UV=$(UV_Q) UV_PYTHON=$(PY_Q) bash scripts/plugin-verify.sh optional

plugin-verify-strict: check-uv ## Check plugin fidelity and require Cortex loader validation
	@command -v cortex >/dev/null 2>&1 || { echo 'Cortex CLI is required. Install it or use plugin-verify for optional loader validation.' >&2; exit 1; }
	UV=$(UV_Q) UV_PYTHON=$(PY_Q) bash scripts/plugin-verify.sh required

##@ Evaluation

.PHONY: eval
eval: check-uv ## Run informational reviewer eval tests
	$(UV_RUN) pytest tests/reviewer_eval/ -q --tb=short

##@ Cleanup

.PHONY: clean-cache clean-venv clean-all
clean-cache: ## Remove project caches and coverage output, excluding virtual environments
	bash scripts/clean.sh cache

clean-venv: ## Remove .venv; prompts on a terminal, FORCE=1 skips the prompt
	FORCE=$(call shq,$(FORCE)) bash scripts/clean.sh venv

clean-all: ## Confirm once, then remove caches and .venv; FORCE=1 skips the prompt
	FORCE=$(call shq,$(FORCE)) bash scripts/clean.sh all

##@ Status

.PHONY: status status-preflight
status: check-uv ## Show project counts and the selected interpreter
	@UV=$(UV_Q) $(UV_RUN) python scripts/dev_info.py status

status-preflight: check-uv ## Check uv availability and lockfile consistency
	@test -f pyproject.toml && test -f uv.lock || { echo 'pyproject.toml and uv.lock must exist in the project root.' >&2; exit 1; }
	$(UV_Q) lock --check
	@echo 'uv is available and the project lockfile is consistent.'

##@ Release

# Release recipes must never reference $(MAKE): make -n executes
# such lines, which would turn a dry run into a real release.
.PHONY: release-bump release-merge
release-bump: ## Validate, bump, sign, and push release/vX.Y.Z (VERSION=X.Y.Z; preview DRY_RUN=1)
	$(call require,VERSION,make release-bump VERSION=X.Y.Z [DRY_RUN=1])
	UV=$(UV_Q) UV_PYTHON=$(PY_Q) DRY_RUN=$(call shq,$(DRY_RUN)) bash scripts/release.sh bump $(call shq,$(VERSION))

release-merge: ## Squash-merge in an isolated worktree, tag, push, draft release (VERSION=X.Y.Z; preview DRY_RUN=1)
	$(call require,VERSION,make release-merge VERSION=X.Y.Z [DRY_RUN=1])
	UV=$(UV_Q) UV_PYTHON=$(PY_Q) DRY_RUN=$(call shq,$(DRY_RUN)) bash scripts/release.sh merge $(call shq,$(VERSION))
