"""Shared test utilities following pytest best practices.

This module provides reusable helper functions for test creation:
- Sample rule file generation
- File content assertion helpers
- Subprocess execution wrappers
- Common test data builders
"""

import re
import subprocess
from pathlib import Path


def create_sample_rule(
    tmp_path: Path,
    filename: str,
    *,
    include_token_budget: bool = True,
    include_keywords: bool = True,
    include_depends: bool = False,
    token_budget: int = 500,
    keywords: str = "test, sample",
    depends: str = "000-global-core.md",
) -> Path:
    """Create a sample rule file for testing.

    Args:
        tmp_path: pytest tmp_path fixture
        filename: Rule filename (e.g., "100-test-rule.md")
        include_token_budget: Whether to include TokenBudget metadata
        include_keywords: Whether to include Keywords metadata
        include_depends: Whether to include Depends metadata
        token_budget: TokenBudget value to use
        keywords: Keywords string to use
        depends: Depends string to use

    Returns:
        Path to created rule file
    """
    # Arrange - Build metadata section
    metadata_lines = []

    if include_keywords:
        metadata_lines.append(f"**Keywords:** {keywords}")
    if include_token_budget:
        metadata_lines.append(f"**TokenBudget:** ~{token_budget}")
    if include_depends:
        metadata_lines.append(f"**Depends:** {depends}")

    metadata = "\n".join(metadata_lines)

    # Arrange - Build rule content
    content = f"""{metadata}

# Test Rule

## Purpose
Test rule generated by create_sample_rule().

## Contract
- **Inputs/Prereqs:** None

## Quick Compliance Checklist
- [ ] Test item

## Validation
Success checks

## Response Template
Template

## References
Links
"""

    # Act - Write file
    rule_file = tmp_path / filename
    rule_file.write_text(content)

    return rule_file


def assert_file_matches_pattern(
    file_path: Path, patterns: list[str], *, multiline: bool = True
) -> None:
    """Assert file content matches all given patterns.

    Args:
        file_path: Path to file to check
        patterns: List of regex patterns that must match
        multiline: Whether to use MULTILINE flag for regex

    Raises:
        AssertionError: If any pattern doesn't match
    """
    content = file_path.read_text()
    flags = re.MULTILINE if multiline else 0

    for pattern in patterns:
        assert re.search(pattern, content, flags), (
            f"Pattern '{pattern}' not found in {file_path.name}"
        )


def assert_file_not_matches_pattern(
    file_path: Path, patterns: list[str], *, multiline: bool = True
) -> None:
    """Assert file content does NOT match given patterns.

    Args:
        file_path: Path to file to check
        patterns: List of regex patterns that must NOT match
        multiline: Whether to use MULTILINE flag for regex

    Raises:
        AssertionError: If any pattern matches
    """
    content = file_path.read_text()
    flags = re.MULTILINE if multiline else 0

    for pattern in patterns:
        assert not re.search(pattern, content, flags), (
            f"Pattern '{pattern}' found in {file_path.name} but should not be present"
        )


def run_script_with_args(
    script_path: Path,
    args: list[str],
    cwd: Path | None = None,
    timeout: int = 30,
) -> tuple[int, str, str]:
    """Run a Python script as subprocess and capture output.

    Args:
        script_path: Path to Python script
        args: Command-line arguments
        cwd: Working directory (optional)
        timeout: Timeout in seconds (default: 30)

    Returns:
        Tuple of (exit_code, stdout, stderr)

    Raises:
        subprocess.TimeoutExpired: If command times out
    """
    import sys

    cmd = [sys.executable, str(script_path), *args]

    result = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        timeout=timeout,
    )

    return result.returncode, result.stdout, result.stderr


def create_mock_agents_template(tmp_path: Path, template_var: str = "{rule_path}") -> Path:
    """Create a mock AGENTS.md template file.

    Args:
        tmp_path: pytest tmp_path fixture
        template_var: Template variable to use (default: {rule_path})

    Returns:
        Path to created AGENTS.md template
    """
    content = f"""# AGENTS.md Template

## How to Load Rules

Rules are located at: {template_var}

## For LLMs and Agents

Load rules from {template_var} directory.
"""

    agents_file = tmp_path / "AGENTS.md"
    agents_file.write_text(content)
    return agents_file


def count_test_markers(test_file: Path) -> dict[str, int]:
    """Count pytest markers in a test file.

    Args:
        test_file: Path to test file

    Returns:
        Dictionary mapping marker names to counts
    """
    content = test_file.read_text()

    markers = {"unit": 0, "integration": 0, "slow": 0}

    for marker in markers:
        pattern = rf"@pytest\.mark\.{marker}\b"
        markers[marker] = len(re.findall(pattern, content))

    return markers


def extract_test_functions(test_file: Path) -> list[str]:
    """Extract test function names from a test file.

    Args:
        test_file: Path to test file

    Returns:
        List of test function names
    """
    content = test_file.read_text()
    pattern = r"def (test_\w+)\("
    return re.findall(pattern, content)
